# Generated by Django 5.0.2 on 2024-03-01 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='contestant_photos')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('last_vote_reset', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_votes', models.PositiveIntegerField(default=0)),
                ('winning_votes', models.PositiveIntegerField(default=0)),
                ('losing_votes', models.PositiveIntegerField(default=0)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.contestant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.task')),
            ],
            options={
                'unique_together': {('contestant', 'task')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contestant_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.contestanttask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.customuser')),
            ],
            options={
                'unique_together': {('user', 'contestant_task')},
            },
        ),
    ]
