# Generated by Django 5.0.2 on 2024-03-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_alter_contestanttask_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
